// Generated by scripts/generate-build-info.mjs. Do not edit.
export const BUILD_INFO = {
  version: "0.1.0-dev+uncommitted",
  commit: "uncommitted",
  channel: "development",
  builtAt: "2026-08-15T08:08:21.007Z",
} as const;
