export const IPC = {
  buildInfo: "app:build-info",
  libraryStatus: "library:status",
  chooseLibrary: "library:choose",
  setLibraryPath: "library:set-path",
  startScan: "library:scan-start",
  cancelScan: "library:scan-cancel",
  scanProgress: "library:scan-progress",
  queryLibrary: "library:query",
  queryLibraryIds: "library:query-ids",
  statistics: "library:statistics",
  getSettings: "settings:get",
  updateSettings: "settings:update",
  getSavedSearches: "saved-searches:get",
  saveSearch: "saved-searches:save",
  deleteSavedSearch: "saved-searches:delete",
  operationHistory: "operations:get",
  copySelectionMetadata: "system:copy-selection-metadata",
  previewDeletion: "deletion:preview",
  executeDeletion: "deletion:execute",
  getQuarantineRecords: "quarantine:get",
  restoreQuarantine: "quarantine:restore",
  copyText: "system:copy-text",
  openExternal: "system:open-external",
} as const;
